---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# binomial

<!-- badges: start -->
<!-- badges: end -->

The goal of the `"binomial"` package is to provide functions for calulating the properties of the binomial random variable, including probabilities, probability distribution, expected value, variance, etc.

## Installation

You can install the released version of binomial from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("binomial")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("stat133-sp19/hw-stat133-yangluanne")
```
## Example

``` {r}
library(binomial)

# binomial random variable
X <- bin_variable(trials = 5, prob = 0.5)
X

# binomial probability
bin_probability(success = 2, trials = 5, prob = 0.5)

# binomial distribution
dist <- bin_distribution(trials = 5, prob = 0.5)
dist

# binomial ditribution plot
plot(dist)

# binomial cumulative distribution
cumu <- bin_cumulative(trials = 5, prob = 0.5)
cumu

# binomial cumulative distribution plot
plot(cumu)

# binomial random variable summary statistics
summary(X)

# summary measures
bin_mean(5, 0.5)
bin_variance(5, 0.5)
bin_mode(5, 0.5)
bin_skewness(5, 0.5)
bin_kurtosis(5, 0.5)

```
